### PR TITLE
feat: adding sail

### PR DESCRIPTION
**Pull request by Arkanius**
## Add Laravel Sail for Simplified Local Development

This PR introduces Laravel Sail, a lightweight and simple way to set up a Docker-based development environment for the project. With Sail, contributors can easily run the application locally with minimal setup.

###  Key Benefits:

* Streamlines local development setup using Docker.
* Ensures consistency across environments.
* Simplifies running the project without additional tooling dependencies.
* This addition makes it easier for new and existing developers to start contributing seamlessly.

### CODE REVIEW

**Comment by paulocastellano** [comment]
Hey @Arkanius 

Thank you for added a Docker support to 🌙

Can you also add redis and mailhog please?

**Review by paulocastellano — APPROVED** [review]

**Comment by paulocastellano** [comment]
@all-contributors please add @Arkanius for <contributions>

**Comment by paulocastellano** [comment]
https://github.com/all-contributors please add @Arkanius for code

**Comment by paulocastellano** [comment]
@all-contributors please add @Arkanius for code

**Comment by paulocastellano** [comment]
@all-contributors please add @Arkanius for code

**Comment by PLP-GTR** [comment]
Hey @paulocastellano @Arkanius 
I love the project! But I'm having problems with sail and cors (white page). Do you think it would be possible for you do update [the docs](https://github.com/luadotsh/docs/blob/main/src/app/local-development/page.mdx)? My experience with sail is practically zero :(

**Comment by paulocastellano** [comment]
Thank you @PLP-GTR 

@Arkanius can you do it?

**Comment by Arkanius** [comment]
@paulocastellano @PLP-GTR sure! I'll start work on that

**Comment by paulocastellano** [comment]
@Arkanius thank you!

**Comment by paulocastellano** [comment]
@PLP-GTR the docs it’s updated.

https://developers.lua.sh

**Pull request merged**
